spring:
  mail:
    host: smtp.qq.com
    username: taskmanager@foxmail.com
    password: zizmlybzouiqdjhc
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  application:
    name: taskmanager
  datasource:
    url: jdbc:mysql://rm-wz968x73ihm8kx49jqo.mysql.rds.aliyuncs.com:3306/task_manager?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: db_manager
    password: ooad2021
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 5000
mybatis-plus:
  type-aliases-package: com.hungry.taskmanager.entity
  mapper-locations: classpath:com/hungry/taskmanager/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl